# Generated by Django 4.2.11 on 2024-04-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
    ]
